baseURL = 'https://m450.frickelbude.ch'
languageCode = 'de-ch'
title = 'Modul 450: Applikationen testen'
enableEmoji = true

[minify]
minifyOutput = true

[params]
math.disable = false
openapi = false
showVisitedLinks = true
themeVariant = 'zen-light'
hideAuthorDate = true
disableInlineCopyToClipboard = true

[params.author]
name = 'Patrick Bucher, BBZW Sursee'

[module]
[[module.imports]]
path = 'github.com/McShelby/hugo-theme-relearn'
